package nl.rabobank.customerstatementservice.mapper;

import nl.rabobank.customerstatementservice.dto.CustomerStatementRecordDto;
import nl.rabobank.customerstatementservice.infrastructure.CustomerStatementRecord;
import org.springframework.stereotype.Service;

// Normally I'd let this be generated by Mapstruct, but I came across an IntelliJ bug..
@Service
public class CustomerStatementMapper {

    public CustomerStatementRecord toCustomerStatementRecord(CustomerStatementRecordDto customerStatementRecordDto) {
        if (customerStatementRecordDto == null) {
            return null;
        }

        CustomerStatementRecord customerStatementRecord = new CustomerStatementRecord();

        customerStatementRecord.setAccountNumber(customerStatementRecordDto.getAccountNumber());
        customerStatementRecord.setDescription(customerStatementRecordDto.getDescription());
        if (customerStatementRecordDto.getEndBalance() != null) {
            customerStatementRecord.setEndBalance(customerStatementRecordDto.getEndBalance());
        }
        if (customerStatementRecordDto.getMutation() != null) {
            customerStatementRecord.setMutation(customerStatementRecordDto.getMutation());
        }
        if (customerStatementRecordDto.getStartBalance() != null) {
            customerStatementRecord.setStartBalance(customerStatementRecordDto.getStartBalance());
        }
        customerStatementRecord.setTransactionReference(customerStatementRecordDto.getTransactionReference());

        return customerStatementRecord;
    }
}
